//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacoesUteis
    {
        public int ID { get; set; }
        public string Assunto { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Destinatario { get; set; }
        public Nullable<int> IdCodigoPostal { get; set; }
    
        public virtual CodigoPostal CodigoPostal { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
