//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocorrencias
    {
        public int ID { get; set; }
        public int IdUtilizador { get; set; }
        public int IdOcorrencias { get; set; }
        public string Descricao { get; set; }
        public string Anexos { get; set; }
    
        public virtual TipoOcorrencias TipoOcorrencias { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
