//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUtilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoUtilizador()
        {
            this.TipoOcorrencias = new HashSet<TipoOcorrencias>();
            this.Utilizadores = new HashSet<Utilizadores>();
        }
    
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoOcorrencias> TipoOcorrencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizadores> Utilizadores { get; set; }
    }
}
