//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizadores()
        {
            this.InformacoesUteis = new HashSet<InformacoesUteis>();
            this.Ocorrencias = new HashSet<Ocorrencias>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public int NumCC { get; set; }
        public Nullable<int> NumEleitor { get; set; }
        public string Morada { get; set; }
        public Nullable<int> IdCodigoPostal { get; set; }
        public string Email { get; set; }
        public string NomeUtilizador { get; set; }
        public string Password { get; set; }
        public byte Estado { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string UserID { get; set; }
    
        public virtual CodigoPostal CodigoPostal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformacoesUteis> InformacoesUteis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocorrencias> Ocorrencias { get; set; }
        public virtual TipoUtilizador TipoUtilizador { get; set; }
    }
}
